### ISSUE TITLE
Set a floor on how much lisk to keep

### ISSUE THREAD

**Issue by Isabello** [karek314/liskpool#1]
Currently, the implementation will dump to a 0 balance. In an effort to prevent errors I am recommending setting a minimum balance to maintain. For example, send until theres only 10 lisk left in the account rather than trying to reach 0

**Comment by karek314** [comment]
I think similar result can be achieved by setting - **payout_threshold** to something greater, like 5 LSK. So in result there will be always some value kept.

**Comment by Isabello** [comment]
sounds fine to me, im just looking at the issues that this has caused.

we are working to resolve the issues in core but in the meantime updating
this software would be the quickest solution
