### ISSUE TITLE
Incorrect Pending Balances

### ISSUE THREAD

**Issue by MorinelloA** [karek314/liskpool#3]
When you call api/info/forged/?by=ADDRESS, and that address has at least one payout, the pending balance actually shows the amount sent to that address at their first payout and not the pending balance.

This also causes the Stats page to show the pending balance incorrectly. You can see how the balance is not the same when compared to the chart, but will match up with the first payout amount:

![image](https://user-images.githubusercontent.com/15217668/45056416-d0ba0100-b060-11e8-89b5-3e5b07ecc4af.png)

**Comment by karek314** [comment]
@MorinelloA Thanks for reporting !
Solved with https://github.com/karek314/liskpool/commit/aeaa3c8b7d0294b160da5fa57e129025a3b9ef0c

Cheers 👍
